# Weather & Play

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_excel('data/weather.xls', index_col=0)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14 entries, 0 to 13
Data columns (total 2 columns):
Weather    14 non-null object
Play       14 non-null object
dtypes: object(2)
memory usage: 336.0+ bytes

In [ ]:
data.head()

    Weather Play
0     Rainy  Yes
1     Sunny  Yes
2  Overcast  Yes
3  Overcast  Yes
4     Sunny   No

In [ ]:
# step 1: tạo bảng crosstab có index là Weather, column là Play
data_crosstab = pd.crosstab(data['Weather'],
                            data['Play'], 
                            margins = False)
data_crosstab

Play      No  Yes
Weather
Overcast   0    5
Rainy      2    2
Sunny      2    3

In [ ]:
data_crosstab['Total'] = data_crosstab['No'] + data_crosstab['Yes']
data_crosstab

Play      No  Yes  Total
Weather
Overcast   0    5      5
Rainy      2    2      4
Sunny      2    3      5

In [ ]:
# Step 2    
# tính xác suất từng Weather
data_crosstab["P_Weather"] = data_crosstab["Total"] / data.shape[0]

In [ ]:
# tính xác suất Play = No
Total_No = sum(data_crosstab["No"].values)
P_No = Total_No/data.shape[0]
P_No

0.2857142857142857

In [ ]:
# tính xác suất Play = Yes
Total_Yes = sum(data_crosstab["Yes"].values)
P_Yes = Total_Yes/data.shape[0]
P_Yes

0.7142857142857143

In [ ]:
# tính P(Weather|Play)
data_crosstab["P_Weather_No"] = data_crosstab["No"]/Total_No
data_crosstab["P_Weather_Yes"] = data_crosstab["Yes"]/Total_Yes

In [ ]:
data_crosstab

Play      No  Yes  Total  P_Weather  P_Weather_No  P_Weather_Yes
Weather
Overcast   0    5      5   0.357143           0.0            0.5
Rainy      2    2      4   0.285714           0.5            0.2
Sunny      2    3      5   0.357143           0.5            0.3

In [ ]:
sum(data_crosstab["Yes"].values)/sum(data_crosstab["Total"].values)

0.7142857142857143

In [ ]:
# Step 3
def predict_target(data, weather):
    # lấy dòng có Weather cần tìm
    event = data.loc[weather,:]
    
    # P(Yes|Weather) = P(Weather|Yes) * P(Yes) / P(Weather)
    P_Yes_event = event['P_Weather_Yes'] * P_Yes / event['P_Weather']
    print(event)
    return P_Yes_event

In [ ]:
P_Yes_Sunny = predict_target(data_crosstab, "Sunny")
P_Yes_Sunny

Play
No               2.000000
Yes              3.000000
Total            5.000000
P_Weather        0.357143
P_Weather_No     0.500000
P_Weather_Yes    0.300000
Name: Sunny, dtype: float64

0.6

In [ ]:
# => If "Sunny" => "Play"